// m42/web/src/components/layout/Sidebar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { LayoutDashboard, Network, Clock, Database, ChevronRight } from 'lucide-vue-next'

const route = useRoute()

const navItems = [
  { path: '/', label: 'Dashboard', icon: LayoutDashboard },
  { path: '/topology', label: 'Topology', icon: Network },
  { path: '/slowlog', label: 'Slowlog', icon: Clock },
]

const isActive = (path: string) => {
  if (path === '/') return route.path === '/'
  return route.path.startsWith(path)
}
</script>

<template>
  <aside class="w-56 min-h-screen flex flex-col border-r border-primary/15 bg-bg-secondary/90 backdrop-blur-md"
    style="box-shadow: 1px 0 20px rgba(0,212,170,0.06);">
    <div class="px-5 py-6 flex items-center gap-3 border-b border-primary/10">
      <div class="w-9 h-9 rounded-lg bg-primary/15 flex items-center justify-center animate-pulse-glow">
        <Database class="w-5 h-5 text-primary" />
      </div>
      <div>
        <h1 class="text-sm font-bold text-primary font-mono tracking-wide glow-text">REDIS</h1>
        <p class="text-[10px] text-gray-500 tracking-widest">CLUSTER MONITOR</p>
      </div>
    </div>

    <nav class="flex-1 py-4 px-3 space-y-1">
      <router-link v-for="item in navItems" :key="item.path" :to="item.path"
        class="flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm transition-all duration-200 group"
        :class="isActive(item.path)
          ? 'bg-primary/12 text-primary border border-primary/20'
          : 'text-gray-400 hover:text-gray-200 hover:bg-white/5'">
        <component :is="item.icon" class="w-4.5 h-4.5" :class="isActive(item.path) ? 'text-primary' : 'text-gray-500 group-hover:text-gray-300'" />
        <span class="flex-1">{{ item.label }}</span>
        <ChevronRight v-if="isActive(item.path)" class="w-3.5 h-3.5 text-primary/60" />
      </router-link>
    </nav>

    <div class="px-5 py-4 border-t border-primary/10">
      <div class="flex items-center gap-2">
        <div class="w-2 h-2 rounded-full bg-primary animate-pulse-glow"></div>
        <span class="text-xs text-gray-500">System Online</span>
      </div>
    </div>
  </aside>
</template>

// m6/src/components/Sidebar.tsx
import React from 'react';
import { Keyboard, FileCode, ScrollText, Settings, Zap, GitBranch } from 'lucide-react';
import { TabType } from '@/types';

interface SidebarProps {
  activeTab: TabType;
  onTabChange: (tab: TabType) => void;
}

export const Sidebar: React.FC<SidebarProps> = ({ activeTab, onTabChange }) => {
  const tabs = [
    { id: 'tasks' as TabType, label: '快捷键任务', icon: <Keyboard className="w-5 h-5" /> },
    { id: 'workflow' as TabType, label: '工作流编排', icon: <GitBranch className="w-5 h-5" /> },
    { id: 'editor' as TabType, label: '脚本编辑器', icon: <FileCode className="w-5 h-5" /> },
    { id: 'logs' as TabType, label: '执行日志', icon: <ScrollText className="w-5 h-5" /> },
    { id: 'settings' as TabType, label: '设置', icon: <Settings className="w-5 h-5" /> },
  ];

  return (
    <div className="w-56 bg-slate-800 border-r border-slate-700 flex flex-col">
      <div className="p-4 border-b border-slate-700">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-cyan-500 rounded-lg flex items-center justify-center">
            <Zap className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-white font-bold text-lg">HotkeyRunner</h1>
            <p className="text-slate-400 text-xs">快捷键自动化</p>
          </div>
        </div>
      </div>

      <nav className="flex-1 p-3 space-y-1">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => onTabChange(tab.id)}
            className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all duration-200 ${
              activeTab === tab.id
                ? 'bg-cyan-600 text-white shadow-lg shadow-cyan-600/25'
                : 'text-slate-300 hover:bg-slate-700 hover:text-white'
            }`}
          >
            {tab.icon}
            {tab.label}
          </button>
        ))}
      </nav>

      <div className="p-3 border-t border-slate-700">
        <div className="text-xs text-slate-500 text-center">
          v0.1.0
        </div>
      </div>
    </div>
  );
};
